[tool.pytest.ini_options]
testpaths = "tests"


[tool.ruff]
extend = "ruff_defaults.toml"
extend-exclude = ["plugin_template"]
target-version = "py38"

[tool.ruff.lint]
unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]
